### ISSUE TITLE
Trying to use plug-in throws malformed URL exception

### ISSUE THREAD

**Issue by stevesarkisian-tribpub** [NicholasAStuart/Maven-Mule-REST-Plugin#17]
Using plug in in Maven with muleApiUrl= "http://tribmuledev.tribpub.com:8080/mmc-console-3.5.3/api"
 
Throws: [ERROR] Failed to execute goal com.github.nicholasastuart:mule-mmc-rest-plugin:1
.2.0:deploy (default-cli) on project axsyncservice: Unable to parse configuratio
n of mojo com.github.nicholasastuart:mule-mmc-rest-plugin:1.2.0:deploy for param
eter muleApiUrl: Cannot convert 'muleApiUrl' to URL: no protocol: muleApiUrl ->
[Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal c
om.github.nicholasastuart:mule-mmc-rest-plugin:1.2.0:deploy (default-cli) on pro
ject axsyncservice: Unable to parse configuration of mojo com.github.nicholasast
uart:mule-mmc-rest-plugin:1.2.0:deploy for parameter muleApiUrl: Cannot convert
'muleApiUrl' to URL

**Comment by NicholasAStuart** [comment]
Is there any chance you can include the XML block you have in your pom.xml?

**Comment by stevesarkisian-tribpub** [comment]
Sure thing:
<plugin>
				<groupId>com.github.nicholasastuart</groupId>
				<artifactId>mule-mmc-rest-plugin</artifactId>
				<version>1.2.2-SNAPSHOT</version>
				<executions>
                                     <execution>
						<id>mule-deploy</id>
						<phase>install</phase>
						<goals>
							<goal>deploy</goal>
						</goals>
						<configuration>
							<name>axsyncservice</name>
							<username>*redacted*</username>
							<password>*redacted*</password>
							<version>$BUILD_VERSION</version>
							<clusterName>Mule-QA-Cluster</clusterName>
							<muleApiURL>http://tribmuledev.tribpub.com:8080/mmc-console-3.5.3/api</muleApiURL>
						</configuration>
					</execution>
				</executions>
				
			</plugin>

**Comment by NicholasAStuart** [comment]
I think the configuration XML might be case sensitive. Try 
```xml
<muleApiUrl>http://tribmuledev.tribpub.com:8080/mmc-console-3.5.3/api</muleApiUrl>
```

**Comment by stevesarkisian-tribpub** [comment]
Same result: 
[ERROR] Failed to execute goal com.github.nicholasastuart:mule-mmc-rest-plugin:1
.2.0:deploy (default-cli) on project axsyncservice: Unable to parse configuratio
n of mojo com.github.nicholasastuart:mule-mmc-rest-plugin:1.2.0:deploy for param
eter muleApiUrl: Cannot convert 'muleApiUrl' to URL: no protocol: muleApiUrl ->
[Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal c
om.github.nicholasastuart:mule-mmc-rest-plugin:1.2.0:deploy (default-cli) on pro
ject axsyncservice: Unable to parse configuration of mojo com.github.nicholasast
uart:mule-mmc-rest-plugin:1.2.0:deploy for parameter muleApiUrl: Cannot convert
'muleApiUrl' to URL

**Comment by stevesarkisian-tribpub** [comment]
I'd considered modifying the code so protocol, host and path can just be passed in as config params, but I wanted to see if you had easier way.

**Comment by NicholasAStuart** [comment]
I've tried your XML, and I think you need to change clusterName to serverGroup. Other than that, everything should work. 

I could make the protocol, host, and path as separate arguments, but for simplicity it's easiest just to put the URL you connect to the MMC with. Your URL isn't improperly formatted, unless there is some hidden unicode character within it that I can't see. 

Try modifying clusterName to serverGroup and changing muleApiURL to muleApiUrl.

**Comment by stevesarkisian-tribpub** [comment]
Can you confirm the command and parameters you are using to run on your side?  

Mine is simply: mvn com.github.nicholasastuart:mule-mmc-rest-plugin:deploy

Error messages are getting stranger:
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-c
li of goal com.github.nicholasastuart:mule-mmc-rest-plugin:1.2.2-SNAPSHOT:deploy
 failed: A required class was missing while executing com.github.nicholasastuart
:mule-mmc-rest-plugin:1.2.2-SNAPSHOT:deploy: org/slf4j/impl/StaticLoggerBinder
-----------------------------------------------------
realm =    plugin>com.github.nicholasastuart:mule-mmc-rest-plugin:1.2.2-SNAPSHOT

**Comment by fertroya** [comment]
Adding my 2 cents here; that error above was due to a [Maven bug](https://issues.apache.org/jira/browse/MNG-5787). After moving to 3.3.9 (fix version) I could call the  `deploy` with no errors.

**Comment by NicholasAStuart** [comment]
No Activity, and @fertroya states this is a Maven bug, so the user should move to that version if they want to resolve this issue.

**Comment by paulcalabro** [comment]
I'm on v3.3.9 and experiencing the same issue:

```
Caused by: java.net.MalformedURLException: no protocol: muleApiUrl
        at java.net.URL.<init>(URL.java:593)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at org.codehaus.plexus.component.configu
```

Any updates on this?

**Comment by paulcalabro** [comment]
(I know it's closed, however, just curious if anyone else has experienced the issue since then and maybe identified a fix)

**Comment by stevesarkisian-tribpub** [comment]
@paulcalabro: we abandoned trying to use pom file for configuring this plugin and simply started passing config parameters via command line.  Haven't experienced the issue since.
